### PR TITLE
Feature/17 add helped me button at articles

### PR DESCRIPTION
**Pull request by andersonfernandes**
- Add Like model model
- Add Likes Controller
- Add button to the article show action

### CODE REVIEW

**Comment by andersonfernandes** [comment]
Hi @AurelienGasser, here's the implementation of the #17 issue.

**Comment by AurelienGasser** [comment]
Thanks a lot for this PR, it looks great! :+1:

In the coming days I'll add follow-up issues:

- add a challenge (captcha-like) to prevent bots from casting likes
- add a client side cookie/localStorage to prevent users from liking the same article twice

Those issues are not blocking so I'm gonna merge this PR now. Thanks again!

**Comment by AurelienGasser** [comment]
I had to apply a hot fix after merging because the new code was automatically deployed but the migrations weren't run. As a result, the article show page would error out completely (500 error)

I'm from my phone so I can't run the migrations! I'll fix this on Monday. 

Hot fix: https://github.com/AurelienGasser/planetocd/commit/4ab3277e24828ec7aca9602d13b896bfb4843893

**Comment by AurelienGasser** [comment]
Second update: I rolled back the deployment to an earlier version. I'll re deploy this PR properly next week.

**Comment by AurelienGasser** [comment]
The feature is now properly deployed in production :tada:

**Pull request merged**
