### PR TITLE
Add pagination to articles

### LINKED ISSUE #38: Add pagination to main list of articles
Add pagination to e.g. https://planetocd.org/es

The pagination component from the article page can be reused, e.g. https://planetocd.org/es/articles/1/obsesion-religiosa-cuando-el-toc-se-mezcla-con-la-religion-y-la-fe

### PR DESCRIPTION
**Pull request by Jamme-D**
fixes #38

Hey, this is what I have so far. I'm still trying to get my developer environment set up. Please let me know how I can improve on this PR. Your feedback is greatly appreciated!

### CODE REVIEW

**Comment by AurelienGasser** [comment]
Hi @Jamme-D, thank you for your PR! 

You made a change to the HTML template, which is a first step, but you also need to make changes to the backend code: currently `$viewModel` doesn't have a `Pagination` property, so `$viewModel.Pagination` will raise an error.

**Comment by Jamme-D** [comment]
Hey, @AurelienGasser, Thanks for your patience and your explanation. Sorry, I'm having trouble being able to run it locally. It doesn't seem like I can get CompileDaemon to work. I'm using a mac and go 1.17.2. I've used this command in the terminal:
```
go install github.com/githubnemo/CompileDaemon
```
Then, when I run
```
make run-local
```
I get this response:
```
./run-local.sh
you need to install CompileDeamon with go get github.com/githubnemo/CompileDaemon
./run-local.sh: line 9: CompileDaemon: command not found
[nodemon] 2.0.14
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): static/css/**/*
[nodemon] watching extensions: less
[nodemon] starting `make css`
make[1]: Nothing to be done for `css'.
[nodemon] clean exit - waiting for changes before restart
```
I'm not sure what I'm doing wrong. So, I haven't been able to see my results in a test environment. Can you offer any suggestions?

**Comment by AurelienGasser** [comment]
@Jamme-D You need to figure out where CompileDaemon got installed on your system, and add that location to your PATH. 

Example on my system

```sh
$ echo $PATH
/home/aurelien/.local/bin:/home/aurelien/bin:/home/aurelien/.local/bin:/home/aurelien/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/aurelien/.yarn/bin/:/home/aurelien/go/bin:/usr/local/go/bin:/home/aurelien/bin:/home/aurelien/.local/bin:/home/aurelien/scripts:/home/aurelien/.krew/bin:/home/aurelien/.fzf/bin:/home/aurelien/.yarn/bin/:/home/aurelien/go/bin:/usr/local/go/bin:/home/aurelien/bin:/home/aurelien/.local/bin:/home/aurelien/scripts:/home/aurelien/.krew/bin
$ echo $PATH | sed 's/:/\n/g' | grep go
/home/aurelien/go/bin
/usr/local/go/bin
/home/aurelien/go/bin
/usr/local/go/bin
$ which CompileDaemon
/home/aurelien/go/bin/CompileDaemon
```

To update your PATH you can see e.g. https://apple.stackexchange.com/questions/12629/how-can-i-add-a-path-to-the-path-environment-variable

**Comment by Jamme-D** [comment]
@AurelienGasser  Wow! Thank you so much for your help. I really appreciate your patience as I work through this problem. You've gone above and beyond!

**Comment by AurelienGasser** [comment]
Superseded by https://github.com/AurelienGasser/planetocd/commit/b701ee99c13d713bb6c60f1b1cedf9033fc682b8

**Pull request closed without merging**
